### ISSUE TITLE
goapp serve not working

### ISSUE THREAD

**Issue by vorcigernix** [google/http2preload#2] opened 2017-01-06 08:44 UTC
This may be something I overlooked, but when I run my app (almost helloworld) with goapp serve, it fails to build. Publishing to gae works fine though. Is this known issue?

**Comment by x1ddos** [comment] 2017-01-06 08:57
Not sure. Let me check.

**Comment by x1ddos** [comment] 2017-01-06 10:09
@vorcigernix I don't see anything in the `github.com/google/http2preload` package that would prevent building your app.

What do you mean by "almost helloworld" and what is error message. Also, why do you think it is related to http2preload package?

**Comment by vorcigernix** [comment] 2017-01-06 12:12
It worked before I added http2preload. Might be something else though. Here is the code:
```
package hello

import (
	"html/template"
	"net/http"

	"github.com/google/http2preload"
)

func init() {
	m, err := http2preload.ReadManifest("push_manifest.json")
	http.Handle("/", m.Handler(handleRoot))
	if err != nil {
		panic(err)
	}

}

func handleRoot(w http.ResponseWriter, r *http.Request) {
	tmpl := template.Must(template.ParseGlob("templates/index.html"))
	if err := tmpl.Execute(w, nil); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}
```

**Comment by x1ddos** [comment] 2017-01-06 12:34
So, what is the actual build failure error message?

**Comment by vorcigernix** [comment] 2017-01-06 12:44
```
ERROR    2017-01-06 12:43:49,409 go_runtime.py:181] Failed to build Go application: (Executed command: /Users/adamsobotka/Downloads/go_appengine/goroot/bin/go-app-builder -app_base /Users/adamsobotka/myblog -arch 6 -dynamic -goroot /Users/adamsobotka/Downloads/go_appengine/goroot -gopath /Users/adamsobotka/Downloads/go_appengine/goroot -nobuild_files ^^$ -incremental_rebuild -unsafe -binary_name _go_app -extra_imports appengine_internal/init -work_dir /var/folders/3v/tmfr7mws3pscthdg02w4m5nm0000gn/T/tmp4CMjldappengine-go-bin -gcflags -I,/Users/adamsobotka/Downloads/go_appengine/goroot/pkg/darwin_amd64_appengine -ldflags -L,/Users/adamsobotka/Downloads/go_appengine/goroot/pkg/darwin_amd64_appengine hello.go)
/var/folders/3v/tmfr7mws3pscthdg02w4m5nm0000gn/T/tmp4CMjldappengine-go-bin/hello.go:7: import /Users/adamsobotka/Downloads/go_appengine/goroot/pkg/darwin_amd64/github.com/google/http2preload.a: object is [darwin amd64 go1.7.1 X:framepointer] expected [darwin amd64 go1.6.3 (appengine-1.9.48) X:none]

2017/01/06 13:43:49 go-app-builder: build timing: 0×skip (0 total), 2×compile (240ms total), 0×link (0 total)
2017/01/06 13:43:49 go-app-builder: failed running compile: exit status 2
```

**Comment by x1ddos** [comment] 2017-01-06 12:56
Your issue is with the local setup. The problem is here: `/Users/adamsobotka/Downloads/go_appengine/goroot/pkg/darwin_amd64/github.com/google/http2preload.a: object is [darwin amd64 go1.7.1 X:framepointer] expected [darwin amd64 go1.6.3 (appengine-1.9.48) X:none]`

The package was compiled with Go1.7 but App Engine is obviously using Go1.6. Try deleting `/Users/adamsobotka/Downloads/go_appengine/goroot/pkg/darwin_amd64/github.com/google/http2preload.a`.

**Comment by x1ddos** [comment] 2017-01-06 12:59
Closing as this is a non-package issue.

**Closed as completed by x1ddos** 2017-01-06 12:59 UTC

**Comment by vorcigernix** [comment] 2017-01-06 13:27
Yeah, thanks, works now.
